### ISSUE TITLE
Configure font, font size, etc?

### ISSUE THREAD

**Issue by jackmaney** [xndcn/symbols-tree-view#9]
I found this package via [Atom's blog](http://blog.atom.io/2015/02/23/new-package-roundup.html), and it looks great. Would it be possible to configure the font size of the items in the tree (and possibly also the font)?

**Comment by xndcn** [comment]
@jackmaney Thank you for your suggestion! I will add option for font size later.

**Comment by tomByrer** [comment]
Looking forward to it; font is too small for me.

**Comment by tomByrer** [comment]
Hacked the `.less` myself:
```less
.list-tree.has-collapsable-children li.list-item {
	margin-left: 9px;  /* 15px = too much wasted space */
}

.symbols-tree-view {
  width: 350px;  /* many functions are OBJECT_NAME.longFunctionName */
  height: 110%;  /* don't need padding, though perhaps .space-pen-div { padding-top:5px } would help */
  font-size: 105%;  /* just big enough; 110% is good also */
  position: relative;
  overflow-y: auto;
  overflow-x: hidden;
}

.symbols-icon-base {
  width: 16px;
  height: 14px;
...
```
Works on my 1600x1200 21" CRT well.  (Hey, why throw out $700 that still works?)
