### ISSUE TITLE
Colors for the Symbol icons (and/or) names

### ISSUE THREAD

**Issue by tabascoeye** [xndcn/symbols-tree-view#90]
How about coloring the icons in the view so that it's even easier to distiguish between what types of symbols the user is looking at?

Options for coloring:
- the icon
- the symbol text
- the line that the symbol is on (probably visually messy/displeasing

in a second step, the colors could even be taken from the uses syntax highlight theme (kind of like "minimap" does it) and then the symbol icon colors would match eas users custom settings.
That would also limit complaints like "why not choose $color instead of $color for $symbol-type?".

Example:
![symbols-tree-view-colors](https://cloud.githubusercontent.com/assets/111893/13011495/5ab397ea-d1a7-11e5-9b52-1106e62eed0d.png)

[note: this example was _not_ matched to my syntax highlighting. Just added colors in the CSS]

**Comment by DangerBlack** [comment]
You can edit the styles.less

in this way

```
span.icon-variable{
    color: red;

}
span.icon-function{
    color: green;
}

```

Not the same but is a start point...

**Comment by tabascoeye** [comment]
That is what I did for the mockup screenshot above. But it would make much more sense to have it bound to the syntax theme so that it is "right" for everybody.

**Comment by DangerBlack** [comment]
yeah you're right! I just posted here for who will come here like me and want a quick and dirt solution...

**Comment by rubenwardy** [comment]
Dear future reader:

1. Edit > Stylesheet
2. Paste this template. My preferences, based on `one dark` theme

        ```less
        span.icon-class {
            // color: green;
        }
        span.icon-variable {
            color: #e06c75;
        }
        span.icon-function {
            color: #61afef;
        }
        span.icon-macro {
            // color: green;
        }
        ```
3. Modify to will. You can use the chrome console to get colors of existing text (View > Developer > Toggle Developer Tools)
4. You'll need to restart Atom to see changes.
